FROM \
    ssidk/bifrost-base:2.0

LABEL \
    name="bifrost-ssi_stamper_check" \
    description="Docker environment for ssi_stamper in bifrost" \
    version="2.0" \
    DBversion="31/07/19" \
    maintainer="kimn@ssi.dk;"
