db.runs.createIndex({"name": 1})
db.runs.createIndex({"samples._id": 1})
db.sample_components.createIndex({"sample._id":1})
db.sample_components.createIndex({"summary.assemblatron:action":1})
db.sample_components.createIndex({"component.name":1})
db.sample_components.createIndex({"sample._id":1, "component._id": 1})
db.sample_components.createIndex({"sample._id":1, "component.name": 1})
db.sample_components.createIndex({"sample._id": 1, "status": 1}, { partialFilterExpression: { summary: { $exists: true } } })
db.sample_components.createIndex({"setup_date":1})
db.samples.createIndex({"reads.R1_md5sum":1}, {unique: true, sparse: true})
db.samples.createIndex({"properties.species":1})
db.samples.createIndex({"properties.provided_species":1})
db.samples.createIndex({"properties.detected_species":1})
db.samples.createIndex({"properties.detected_species":1, "name": 1})
db.samples.createIndex({"properties.provided_species":1, "name": 1})
db.samples.createIndex({"sample_sheet.group":1})
db.samples.createIndex({"name":1})