columns = ['name', 'supplying_lab', 'run_name', '_id',
            'input_read_status', 'emails', 'user',
            'R1_location', 'R2_location',
            'provided_species',
            'qcquickie_name_classified_species_1',
            'qcquickie_percent_classified_species_1',
            'qcquickie_name_classified_species_2',
            'qcquickie_percent_classified_species_2',
            'qcquickie_percent_unclassified',
            'qcquickie_bin_length_at_1x',
            'qcquickie_bin_length_at_10x',
            'qcquickie_bin_length_at_25x',
            'qcquickie_bin_length_1x_25x_diff',
            'qcquickie_bin_coverage_at_1x',
            'qcquickie_bin_coverage_at_10x',
            'qcquickie_bin_coverage_at_25x',
            'qcquickie_bin_contigs_at_1x',
            'qcquickie_bin_contigs_at_10x',
            'qcquickie_N50', 'qcquickie_N75',
            'qcquickie_snp_filter_deletions',
            'qcquickie_snp_filter_indels',
            'qcquickie_snp_filter_10x_10%',
            'assembly_bin_length_at_1x',
            'assembly_bin_length_at_10x',
            'assembly_bin_length_at_25x',
            'assembly_bin_length_1x_25x_diff',
            'assembly_bin_coverage_at_1x',
            'assembly_bin_coverage_at_10x',
            'assembly_bin_coverage_at_25x',
            'assembly_bin_contigs_at_1x',
            'assembly_bin_contigs_at_10x',
            'assembly_N50', 'assembly_N75',
            'assembly_snp_filter_deletions',
            'assembly_snp_filter_indels',
            'assembly_snp_filter_10x_10%', 'comments']
